version: "3"

services:
  l11-app:
    build:
      context: ./_docker/php/8.3
      dockerfile: Dockerfile
      args:
        USER: "${DOCKER_USER}"
        UID: "${DOCKER_UID}"
    image: l11-app
    container_name: l11-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    networks:
      - l11-net

  l11-nginx:
    build:
      context: ./_docker/nginx
      dockerfile: Dockerfile
    image: l11-nginx
    container_name: l11-nginx
    environment:
      NGINX_HOST: "${DOCKER_SERVER_NAME}"
      NGINX_LISTEN_PORT: "${DOCKER_NGINX_LISTEN_PORT}"
    restart: unless-stopped
    ports:
      - "${DOCKER_NGINX_PORT}:${DOCKER_NGINX_LISTEN_PORT}"
    volumes:
      - ./backend:/var/www/html
#      - ./_docker/data/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - l11-net

  l11-db:
    image: mysql:8.3.0
    container_name: l11-db
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_USER: "${DB_USERNAME}"
      SERVICES_TAGS: dev
      SERVICES_NAME: mysql
    ports:
      - "${DOCKER_MYSQL_PORT}:${DB_PORT}"
    volumes:
      - ./_docker/data/mysql:/var/lib/mysql
      - ./_docker/mysql:/docker-entrypoint-initdb.d
    networks:
      - l11-net

  l11-redis:
    image: redis:alpine
    container_name: l11-redis
    restart: unless-stopped
    volumes:
      - ./_docker/data/redis:/data
    networks:
      - l11-net

  l11-node:
    build:
      context: ./_docker/node
      dockerfile: Dockerfile
    container_name: l11-node
    restart: unless-stopped
    ports:
      - "${DOCKER_NODE_PORT}:8080"
    working_dir: /var/www
    volumes:
      - ./frontend/:/var/www
    networks:
      - l11-net


networks:
  l11-net:
    driver: bridge
